# Generated by Django 3.2.11 on 2022-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celcius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(max_length=100)),
                ('temeperature', models.FloatField(max_length=100)),
                ('oventemperature', models.IntegerField(max_length=100)),
            ],
        ),
    ]
