# Generated by Django 3.2.11 on 2022-01-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzysystemes', '0002_alter_celcius_oventemperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=100)),
            ],
        ),
    ]
