# Generated by Django 3.2.11 on 2022-01-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzysystemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celcius',
            name='oventemperature',
            field=models.IntegerField(),
        ),
    ]
